
export const VENDORS = [
  {
    id: "techzone",
    name: "TechZone Electronics",
    category: "Electronics",
    categoryColor: "#2563eb",
    categoryBg: "rgba(37,99,235,0.10)",
    city: "Lahore",
    description: "Premium electronics & gadgets — phones, laptops, accessories & more.",
    rating: 4.8,
    reviews: 1240,
    products: 320,
    verified: true,
    featured: true,
    installments: true,
    emoji: "🔌",
    bannerGrad: "linear-gradient(135deg, #1d4ed8 0%, #7c3aed 100%)",
    established: "2022",
    themeBgLight: "#f0f9ff",
    themeColor: "#2563eb",
  },
  {
    id: "homekart",
    name: "HomeKart Pakistan",
    category: "Home & Living",
    categoryColor: "#059669",
    categoryBg: "rgba(5,150,105,0.10)",
    city: "Karachi",
    description: "Appliances, furniture & packages — complete home solutions.",
    rating: 4.6,
    reviews: 875,
    products: 210,
    verified: true,
    featured: true,
    installments: true,
    emoji: "🏠",
    bannerGrad: "linear-gradient(135deg, #047857 0%, #0891b2 100%)",
    established: "2021",
    themeBgLight: "#f0fdf4",
    themeColor: "#059669",
  },
  {
    id: "megadeal",
    name: "MegaDeal Motors",
    category: "Motors & Energy",
    categoryColor: "#7c3aed",
    categoryBg: "rgba(124,58,237,0.10)",
    city: "Islamabad",
    description: "Vehicles, solar & heavy items — all on easy installments.",
    rating: 4.7,
    reviews: 560,
    products: 95,
    verified: true,
    featured: true,
    installments: true,
    emoji: "🚗",
    bannerGrad: "linear-gradient(135deg, #6d28d9 0%, #db2777 100%)",
    established: "2023",
    themeBgLight: "#faf5ff",
    themeColor: "#7c3aed",
  },
  {
    id: "solarpk",
    name: "SolarPK Solutions",
    category: "Solar & Energy",
    categoryColor: "#d97706",
    categoryBg: "rgba(217,119,6,0.10)",
    city: "Lahore",
    description: "Go green with premium solar panels & energy systems.",
    rating: 4.9,
    reviews: 420,
    products: 68,
    verified: true,
    featured: false,
    installments: true,
    emoji: "☀️",
    bannerGrad: "linear-gradient(135deg, #b45309 0%, #f59e0b 100%)",
    established: "2023",
    themeBgLight: "#fff7ed",
    themeColor: "#d97706",
  },
  {
    id: "jazbajahez",
    name: "Jazba Jahez Store",
    category: "Jahez & Dowry",
    categoryColor: "#be185d",
    categoryBg: "rgba(190,24,93,0.10)",
    city: "Faisalabad",
    description: "Complete jahez packages — furniture, appliances & bedding bundles.",
    rating: 4.5,
    reviews: 980,
    products: 145,
    verified: true,
    featured: false,
    installments: true,
    emoji: "🎁",
    bannerGrad: "linear-gradient(135deg, #9d174d 0%, #7c3aed 100%)",
    established: "2021",
    themeBgLight: "#fdf2f8",
    themeColor: "#be185d",
  },
  {
    id: "bikeworld",
    name: "BikeWorld Pakistan",
    category: "Bikes & Scooters",
    categoryColor: "#0891b2",
    categoryBg: "rgba(8,145,178,0.10)",
    city: "Rawalpindi",
    description: "Honda, Yamaha & electric bikes — all models on installments.",
    rating: 4.4,
    reviews: 670,
    products: 87,
    verified: true,
    featured: false,
    installments: true,
    emoji: "🏍️",
    bannerGrad: "linear-gradient(135deg, #0e7490 0%, #1d4ed8 100%)",
    established: "2022",
    themeBgLight: "#ecfdf5",
    themeColor: "#0891b2",
  },
  {
    id: "furniturehub",
    name: "Furniture Hub PK",
    category: "Furniture",
    categoryColor: "#92400e",
    categoryBg: "rgba(146,64,14,0.10)",
    city: "Multan",
    description: "Bedroom sets, sofas & office furniture — crafted with quality.",
    rating: 4.3,
    reviews: 340,
    products: 192,
    verified: false,
    featured: false,
    installments: false,
    emoji: "🛋️",
    bannerGrad: "linear-gradient(135deg, #78350f 0%, #92400e 100%)",
    established: "2023",
    themeBgLight: "#fefce8",
    themeColor: "#92400e",
  },
  {
    id: "mobilezone",
    name: "MobileZone Official",
    category: "Mobiles",
    categoryColor: "#2563eb",
    categoryBg: "rgba(37,99,235,0.10)",
    city: "Karachi",
    description: "Official reseller of Samsung, iPhone, Xiaomi & more brands.",
    rating: 4.7,
    reviews: 2100,
    products: 450,
    verified: true,
    featured: true,
    installments: true,
    emoji: "📱",
    bannerGrad: "linear-gradient(135deg, #1e40af 0%, #0891b2 100%)",
    established: "2020",
    themeBgLight: "#f0f9ff",
    themeColor: "#2563eb",
  },
  {
    id: "rawstore",
    name: "RawStore Materials",
    category: "Raw Materials",
    categoryColor: "#374151",
    categoryBg: "rgba(55,65,81,0.10)",
    city: "Sialkot",
    description: "Construction & industrial raw materials at wholesale prices.",
    rating: 4.2,
    reviews: 210,
    products: 310,
    verified: false,
    featured: false,
    installments: false,
    emoji: "🧱",
    bannerGrad: "linear-gradient(135deg, #1f2937 0%, #374151 100%)",
    established: "2024",
    themeBgLight: "#f3f4f6",
    themeColor: "#374151",
  },
];
