
export const VENDORS = [
  {
    id: 'techzone',
    name: 'TechZone Electronics',
    category: 'Electronics',
    categoryColor: '#2563eb',
    categoryBg: 'rgba(37, 99, 235, 0.10)',
    themeColor: '#2563eb',
    themeBgLight: '#f0f9ff',
    bannerGrad: 'linear-gradient(135deg, #1d4ed8 0%, #2563eb 100%)',
    city: 'Lahore',
    description: 'Premium electronics & gadgets — phones, laptops, accessories & more.',
    rating: 4.8,
    reviews: 1240,
    products: 320,
    verified: true,
    featured: true,
    installments: true,
    emoji: '⚡',
    established: '2022',
    g1: '#6366f1',
    g2: '#4f46e5',
    e: '⚡',
    bar: '#6366f1',
    cat: 'Electronics',
    catC: '#2563eb',
    catBg: '#dbeafe',
    desc: 'Premium electronics & gadgets',
    rat: 4.8,
    prods: 320,
  },
  {
    id: 'homekart',
    name: 'HomeKart Pakistan',
    category: 'Home & Living',
    categoryColor: '#059669',
    categoryBg: 'rgba(5, 150, 105, 0.10)',
    themeColor: '#059669',
    themeBgLight: '#f0fdf4',
    bannerGrad: 'linear-gradient(135deg, #047857 0%, #0891b2 100%)',
    city: 'Karachi',
    description: 'Appliances, furniture & packages — complete home solutions.',
    rating: 4.6,
    reviews: 875,
    products: 210,
    verified: true,
    featured: true,
    installments: true,
    emoji: '🏠',
    established: '2021',
    g1: '#10b981',
    g2: '#0d9488',
    e: '🏠',
    bar: '#10b981',
    cat: 'Home & Living',
    catC: '#059669',
    catBg: '#ecfdf5',
    desc: 'Appliances, furniture & packages',
    rat: 4.6,
    prods: 210,
  },
  {
    id: 'megadeal',
    name: 'MegaDeal Motors',
    category: 'Motors & Energy',
    categoryColor: '#7c3aed',
    categoryBg: 'rgba(124, 58, 237, 0.10)',
    themeColor: '#7c3aed',
    themeBgLight: '#faf5ff',
    bannerGrad: 'linear-gradient(135deg, #6d28d9 0%, #7c3aed 100%)',
    city: 'Islamabad',
    description: 'Vehicles, solar & heavy items — powered for your dreams.',
    rating: 4.7,
    reviews: 645,
    products: 180,
    verified: true,
    featured: false,
    installments: true,
    emoji: '🚗',
    established: '2020',
    g1: '#8b5cf6',
    g2: '#6d28d9',
    e: '🚗',
    bar: '#8b5cf6',
    cat: 'Motors & Energy',
    catC: '#7c3aed',
    catBg: '#f5f3ff',
    desc: 'Vehicles, solar & heavy items',
    rat: 4.7,
    prods: 180,
  },
  {
    id: 'furnish',
    name: 'Furnish Hub',
    category: 'Furniture',
    categoryColor: '#92400e',
    categoryBg: 'rgba(146, 64, 14, 0.10)',
    themeColor: '#92400e',
    themeBgLight: '#fefce8',
    bannerGrad: 'linear-gradient(135deg, #78350f 0%, #92400e 100%)',
    city: 'Multan',
    description: 'Beautiful furniture for homes & offices — comfort meets elegance.',
    rating: 4.5,
    reviews: 523,
    products: 145,
    verified: true,
    featured: false,
    installments: true,
    emoji: '🛋️',
    established: '2019',
    g1: '#d97706',
    g2: '#92400e',
    e: '🛋️',
    bar: '#d97706',
    cat: 'Furniture',
    catC: '#92400e',
    catBg: '#fef3c7',
    desc: 'Furniture for homes & offices',
    rat: 4.5,
    prods: 145,
  },
  {
    id: 'jahezbazar',
    name: 'Jahez Bazaar',
    category: 'Jahez & Weddings',
    categoryColor: '#be185d',
    categoryBg: 'rgba(190, 24, 93, 0.10)',
    themeColor: '#be185d',
    themeBgLight: '#fdf2f8',
    bannerGrad: 'linear-gradient(135deg, #be123c 0%, #be185d 100%)',
    city: 'Lahore',
    description: 'Complete jahez packages for weddings — tradition meets convenience.',
    rating: 4.9,
    reviews: 987,
    products: 210,
    verified: true,
    featured: true,
    installments: true,
    emoji: '📦',
    established: '2020',
    g1: '#ec4899',
    g2: '#be185d',
    e: '📦',
    bar: '#ec4899',
    cat: 'Jahez',
    catC: '#be185d',
    catBg: '#fce7f3',
    desc: 'Jahez packages for weddings',
    rat: 4.9,
    prods: 210,
  },
  {
    id: 'bikezone',
    name: 'BikeZone Pakistan',
    category: 'Motorcycles',
    categoryColor: '#0369a1',
    categoryBg: 'rgba(3, 105, 161, 0.10)',
    themeColor: '#0369a1',
    themeBgLight: '#ecfdf5',
    bannerGrad: 'linear-gradient(135deg, #0c4a6e 0%, #0369a1 100%)',
    city: 'Faisalabad',
    description: 'Latest bikes & motorcycles — ride in style on easy installments.',
    rating: 4.7,
    reviews: 756,
    products: 95,
    verified: true,
    featured: false,
    installments: true,
    emoji: '🏍️',
    established: '2021',
    g1: '#06b6d4',
    g2: '#0369a1',
    e: '🏍️',
    bar: '#06b6d4',
    cat: 'Motorcycles',
    catC: '#0369a1',
    catBg: '#cffafe',
    desc: 'Bikes & motorcycles',
    rat: 4.7,
    prods: 95,
  },
  {
    id: 'solarmax',
    name: 'SolarMax Energy',
    category: 'Solar & Energy',
    categoryColor: '#ea580c',
    categoryBg: 'rgba(234, 88, 12, 0.10)',
    themeColor: '#ea580c',
    themeBgLight: '#fff7ed',
    bannerGrad: 'linear-gradient(135deg, #c2410c 0%, #ea580c 100%)',
    city: 'Karachi',
    description: 'Solar systems & renewable energy — go green, save money.',
    rating: 4.8,
    reviews: 612,
    products: 78,
    verified: true,
    featured: true,
    installments: true,
    emoji: '☀️',
    established: '2022',
    g1: '#f97316',
    g2: '#ea580c',
    e: '☀️',
    bar: '#f97316',
    cat: 'Solar & Energy',
    catC: '#ea580c',
    catBg: '#fed7aa',
    desc: 'Solar systems & renewable energy',
    rat: 4.8,
    prods: 78,
  },
  {
    id: 'digiworld',
    name: 'DigiWorld',
    category: 'Electronics',
    categoryColor: '#2563eb',
    categoryBg: 'rgba(37, 99, 235, 0.10)',
    themeColor: '#2563eb',
    themeBgLight: '#f0f9ff',
    bannerGrad: 'linear-gradient(135deg, #1e40af 0%, #2563eb 100%)',
    city: 'Rawalpindi',
    description: 'Digital devices & accessories — cutting-edge tech at affordable prices.',
    rating: 4.6,
    reviews: 834,
    products: 267,
    verified: true,
    featured: false,
    installments: true,
    emoji: '📱',
    established: '2023',
    g1: '#3b82f6',
    g2: '#2563eb',
    e: '📱',
    bar: '#3b82f6',
    cat: 'Electronics',
    catC: '#2563eb',
    catBg: '#dbeafe',
    desc: 'Digital devices & accessories',
    rat: 4.6,
    prods: 267,
  },
  {
    id: 'kitchendreams',
    name: 'Kitchen Dreams',
    category: 'Home & Living',
    categoryColor: '#059669',
    categoryBg: 'rgba(5, 150, 105, 0.10)',
    themeColor: '#059669',
    themeBgLight: '#f0fdf4',
    bannerGrad: 'linear-gradient(135deg, #065f46 0%, #059669 100%)',
    city: 'Quetta',
    description: 'Kitchen appliances & cookware — make cooking a joy.',
    rating: 4.4,
    reviews: 412,
    products: 156,
    verified: false,
    featured: false,
    installments: true,
    emoji: '🍳',
    established: '2023',
    g1: '#14b8a6',
    g2: '#059669',
    e: '🍳',
    bar: '#14b8a6',
    cat: 'Home & Living',
    catC: '#059669',
    catBg: '#ecfdf5',
    desc: 'Kitchen appliances & cookware',
    rat: 4.4,
    prods: 156,
  },
]
